language: python
python:
  - "3.6"

install: pip install mkdocs mkdocs-material

script: 
  - mkdocs build
  - cp ./CNAME ./site/CNAME

deploy:
  provider: pages
  repo: "Blockchain-zju/blockchain-zju.github.io"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: site
  target_branch: master
  on:
    branch: master