language: python
python:
  - "3.6"

install: pip install mkdocs mkdocs-material

script: mkdocs build

before-deploy:
  - git config --local user.name "yyh1102"
  - git config --local user.email "yyh951102@163.com"

deploy:
  provider: pages
  repo: "Blockchain-zju/blockchain-zju.github.io"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: site
  on:
    branch: master