site_name: ZJUBCA Documents
nav:
  - 致协会成员的一封信: index.md
  - 协会介绍: 
    - 协会简介: info/index.md
    - 协会架构: info/structure.md
    - 合作伙伴: info/partner.md
    - 协会成就: info/achieve.md
  - 协会产品线:
    - Wallet: products/wallet.md
    - EOSToolkit: products/eostoolkit.md
    - 共享计划: products/references.md
  - Dapps:
    - 介绍: dapps/index.md
    - DotA: dapps/DotA.md
    - Ingreos: dapps/ingreos.md
    - GirlGene: dapps/girlgene.md

repo_url: https://github.com/Blockchain-zju/zjubca.docs
theme: 
  name: 'material'
copyright: '浙江大学区块链协会'
lang: ['zh_CN']